"""
Moderation Reports & Statistics
=================================
Generates moderation activity reports for group admins.

Report types:
  • On-demand — generated by /report for the requesting group
  • Reusable period report — generated for a configurable number of days

Delivery:
  • Sent to the mod-log channel if configured (/setmodlog)
  • Or directly to the requesting admin
  • Daily/weekly automatic delivery is not claimed here; Celery beat currently
    runs trust-score maintenance only.

Metrics reported:
  - Recorded moderation actions (delete / mute / ban / warn) with counts
  - Top violation categories (spam / toxic / nsfw / phishing / evasion)
  - Top 5 users attributed to recorded moderation actions
  - Newly activated raid lockdowns
  - Circuit-breaker suppressions observed for the group
  - CAPTCHA pass/fail counts
  - False positives recorded through /falsepositive
"""
from __future__ import annotations

from dataclasses import dataclass, field
from datetime import UTC, datetime, timedelta

from config.settings import get_settings
from src.utils.logger import get_logger
from src.utils.redis_client import get_redis

logger = get_logger(__name__)


@dataclass
class ModerationReport:
    chat_id: int
    period_start: datetime
    period_end: datetime
    total_processed: int = 0
    actions: dict[str, int] = field(default_factory=dict)
    violations: dict[str, int] = field(default_factory=dict)
    raids: int = 0
    captcha_pass: int = 0
    captcha_fail: int = 0
    top_offenders: list[tuple[int, int]] = field(default_factory=list)
    circuit_trips: int = 0
    false_positives: int = 0
    layer_failures: dict[str, int] = field(default_factory=dict)


async def record_action_stat(
    chat_id: int,
    action: str,
    violation: str,
    user_id: int | None = None,
) -> None:
    """Record a moderation action and optionally attribute it to a user."""
    redis = await get_redis()
    settings = get_settings()
    prefix = settings.redis_prefix
    today = datetime.now(tz=UTC).strftime("%Y%m%d")

    action_key = f"{prefix}stats:{chat_id}:{today}:actions"
    viol_key = f"{prefix}stats:{chat_id}:{today}:violations"
    await redis.hincrby(action_key, action, 1)
    await redis.hincrby(viol_key, violation, 1)
    await redis.expire(action_key, 86400 * 35)
    await redis.expire(viol_key, 86400 * 35)

    if user_id is not None:
        offender_key = f"{prefix}stats:{chat_id}:{today}:offenders"
        await redis.zincrby(offender_key, 1, str(user_id))
        await redis.expire(offender_key, 86400 * 35)


async def record_raid_stat(chat_id: int) -> None:
    """Record one newly activated raid lockdown for a group and day."""
    redis = await get_redis()
    settings = get_settings()
    today = datetime.now(tz=UTC).strftime("%Y%m%d")
    key = f"{settings.redis_prefix}stats:{chat_id}:{today}:events"
    await redis.hincrby(key, "raids", 1)
    await redis.expire(key, 86400 * 35)


async def record_circuit_suppression(chat_id: int) -> None:
    """Record a punitive action suppressed by the global circuit breaker."""
    redis = await get_redis()
    settings = get_settings()
    today = datetime.now(tz=UTC).strftime("%Y%m%d")
    key = f"{settings.redis_prefix}stats:{chat_id}:{today}:events"
    await redis.hincrby(key, "circuit_trips", 1)
    await redis.expire(key, 86400 * 35)


async def record_layer_failure(chat_id: int, layer_name: str) -> None:
    """Record a pipeline layer failure for operational diagnostics."""
    redis = await get_redis()
    settings = get_settings()
    today = datetime.now(tz=UTC).strftime("%Y%m%d")
    key = f"{settings.redis_prefix}stats:{chat_id}:{today}:layer_failures"
    await redis.hincrby(key, layer_name, 1)
    await redis.expire(key, 86400 * 35)


async def record_captcha_result(chat_id: int, passed: bool) -> None:
    redis = await get_redis()
    settings = get_settings()
    today = datetime.now(tz=UTC).strftime("%Y%m%d")
    field_name = "pass" if passed else "fail"
    key = f"{settings.redis_prefix}stats:{chat_id}:{today}:captcha"
    await redis.hincrby(key, field_name, 1)
    await redis.expire(key, 86400 * 35)


async def generate_report(chat_id: int, days: int = 7) -> ModerationReport:
    """Generate a moderation report for the last N days."""
    redis = await get_redis()
    settings = get_settings()
    prefix = settings.redis_prefix

    now = datetime.now(tz=UTC)
    start = now - timedelta(days=days)
    report = ModerationReport(
        chat_id=chat_id,
        period_start=start,
        period_end=now,
    )

    # Iterate over days in the window
    actions_total: dict[str, int] = {}
    violations_total: dict[str, int] = {}
    captcha_pass = 0
    captcha_fail = 0
    raids = 0
    circuit_trips = 0
    top_offenders: dict[int, int] = {}
    layer_failures_total: dict[str, int] = {}

    for day_offset in range(days):
        day = (now - timedelta(days=day_offset)).strftime("%Y%m%d")

        # Actions
        actions_raw = await redis.hgetall(f"{prefix}stats:{chat_id}:{day}:actions")
        for k, v in actions_raw.items():
            k = k.decode() if isinstance(k, bytes) else k
            v = int(v)
            actions_total[k] = actions_total.get(k, 0) + v

        # Violations
        viol_raw = await redis.hgetall(f"{prefix}stats:{chat_id}:{day}:violations")
        for k, v in viol_raw.items():
            k = k.decode() if isinstance(k, bytes) else k
            v = int(v)
            violations_total[k] = violations_total.get(k, 0) + v

        # CAPTCHA
        cap_raw = await redis.hgetall(f"{prefix}stats:{chat_id}:{day}:captcha")
        captcha_pass += int(cap_raw.get("pass", b"0"))
        captcha_fail += int(cap_raw.get("fail", b"0"))

        # Raid and circuit events
        events_raw = await redis.hgetall(f"{prefix}stats:{chat_id}:{day}:events")
        raids += int(events_raw.get("raids", b"0"))
        circuit_trips += int(events_raw.get("circuit_trips", b"0"))

        # Layer failures are accumulated across the requested period.
        failures_raw = await redis.hgetall(
            f"{prefix}stats:{chat_id}:{day}:layer_failures"
        )
        for layer_name, value in failures_raw.items():
            layer_name = layer_name.decode() if isinstance(layer_name, bytes) else layer_name
            layer_failures_total[layer_name] = layer_failures_total.get(layer_name, 0) + int(value)

        # Offenders are accumulated across the requested period.
        offenders_raw = await redis.zrange(
            f"{prefix}stats:{chat_id}:{day}:offenders", 0, -1, withscores=True
        )
        for raw_user_id, score in offenders_raw:
            decoded_user_id = raw_user_id.decode() if isinstance(raw_user_id, bytes) else raw_user_id
            try:
                user_id = int(decoded_user_id)
            except (TypeError, ValueError):
                continue
            top_offenders[user_id] = top_offenders.get(user_id, 0) + int(score)

    report.actions = actions_total
    report.violations = violations_total
    report.total_processed = sum(actions_total.values())
    report.captcha_pass = captcha_pass
    report.captcha_fail = captcha_fail
    report.raids = raids
    report.circuit_trips = circuit_trips
    report.top_offenders = sorted(
        top_offenders.items(), key=lambda item: item[1], reverse=True
    )[:5]
    report.layer_failures = dict(
        sorted(layer_failures_total.items(), key=lambda item: item[1], reverse=True)
    )

    # False positives
    fp_val = await redis.get(f"{prefix}false_positives:{chat_id}")
    report.false_positives = int(fp_val or 0)

    return report


def format_report(report: ModerationReport, days: int = 7) -> str:
    """Format a ModerationReport as a Markdown message."""
    period = f"{report.period_start.strftime('%Y-%m-%d')} → {report.period_end.strftime('%Y-%m-%d')}"

    lines = [
        "📊 *تقرير الإشراف | Moderation Report*",
        f"🗓 الفترة | Period: `{period}`",
        f"📝 الإجراءات الكلية | Total Actions: *{report.total_processed}*\n",
    ]

    if report.actions:
        lines.append("*🔨 الإجراءات | Actions:*")
        for action, count in sorted(report.actions.items(), key=lambda x: -x[1]):
            lines.append(f"  `{action:<15}` {count}")
        lines.append("")

    if report.violations:
        lines.append("*⚠️ المخالفات | Violations:*")
        for viol, count in sorted(report.violations.items(), key=lambda x: -x[1]):
            lines.append(f"  `{viol:<15}` {count}")
        lines.append("")

    if report.captcha_pass + report.captcha_fail > 0:
        total_captcha = report.captcha_pass + report.captcha_fail
        pass_rate = report.captcha_pass / total_captcha * 100
        lines.append(
            f"*🔐 CAPTCHA:* {report.captcha_pass}✅ / {report.captcha_fail}❌ "
            f"({pass_rate:.0f}% pass)"
        )

    if report.raids > 0:
        lines.append(f"*🚨 Raids:* {report.raids}")

    if report.circuit_trips > 0:
        lines.append(f"*🛑 Circuit suppressions:* {report.circuit_trips}")

    if report.top_offenders:
        lines.append("*👤 Top offenders:*")
        lines.extend(f"  `{user_id}` — {count}" for user_id, count in report.top_offenders)

    if report.layer_failures:
        lines.append("*⚠️ Pipeline layer failures:*")
        lines.extend(
            f"  `{layer_name}` — {count}"
            for layer_name, count in report.layer_failures.items()
        )

    if report.false_positives > 0:
        lines.append(f"*📌 False Positives:* {report.false_positives}")

    return "\n".join(lines)
