"""initial guardian schema

Revision ID: e28d7e1c3e09
Revises: 
Create Date: 2026-08-18 18:58:07.633314

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy import Text
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'e28d7e1c3e09'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('blacklisted_patterns',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('pattern', sa.Text(), nullable=False),
    sa.Column('pattern_type', sa.String(length=64), nullable=False),
    sa.Column('category', sa.String(length=64), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('bundles',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('title_ar', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('bundle_price', sa.Float(), nullable=False),
    sa.Column('original_price', sa.Float(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('valid_until', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('coupons',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('code', sa.String(length=64), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('discount_percent', sa.Float(), nullable=True),
    sa.Column('discount_fixed', sa.Float(), nullable=True),
    sa.Column('max_discount', sa.Float(), nullable=True),
    sa.Column('min_order_amount', sa.Float(), nullable=False),
    sa.Column('usage_limit', sa.Integer(), nullable=True),
    sa.Column('usage_count', sa.Integer(), nullable=False),
    sa.Column('per_user_limit', sa.Integer(), nullable=False),
    sa.Column('valid_from', sa.DateTime(timezone=True), nullable=True),
    sa.Column('valid_until', sa.DateTime(timezone=True), nullable=True),
    sa.Column('allowed_services', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), "postgresql"), nullable=False),
    sa.Column('allowed_users', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), "postgresql"), nullable=False),
    sa.Column('allowed_levels', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), "postgresql"), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('stackable', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_coupons_code'), 'coupons', ['code'], unique=True)
    op.create_table('domain_reputation',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('domain', sa.String(length=512), nullable=False),
    sa.Column('risk_score', sa.Float(), nullable=False),
    sa.Column('is_phishing', sa.Boolean(), nullable=False),
    sa.Column('is_known_spam', sa.Boolean(), nullable=False),
    sa.Column('labels', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), "postgresql"), nullable=False),
    sa.Column('source', sa.String(length=128), nullable=True),
    sa.Column('checked_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_domain_reputation_domain'), 'domain_reputation', ['domain'], unique=True)
    op.create_table('groups',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=True),
    sa.Column('username', sa.String(length=128), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('raid_lockdown', sa.Boolean(), nullable=False),
    sa.Column('slow_mode_active', sa.Boolean(), nullable=False),
    sa.Column('settings', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), "postgresql"), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('service_categories',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('name_ar', sa.String(length=128), nullable=False),
    sa.Column('icon', sa.String(length=8), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('shop_users',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('telegram_id', sa.BigInteger(), nullable=False),
    sa.Column('username', sa.String(length=128), nullable=True),
    sa.Column('first_name', sa.String(length=255), nullable=True),
    sa.Column('balance', sa.Float(), nullable=False),
    sa.Column('locked_balance', sa.Float(), nullable=False),
    sa.Column('level', sa.Enum('BRONZE', 'SILVER', 'GOLD', 'ELITE', name='userlevel'), nullable=False),
    sa.Column('xp', sa.Integer(), nullable=False),
    sa.Column('vip_tier', sa.Enum('BASIC', 'PRO', 'ELITE', name='viptier'), nullable=False),
    sa.Column('vip_expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('total_spent', sa.Float(), nullable=False),
    sa.Column('total_orders', sa.Integer(), nullable=False),
    sa.Column('referral_code', sa.String(length=32), nullable=False),
    sa.Column('referred_by', sa.BigInteger(), nullable=True),
    sa.Column('is_banned', sa.Boolean(), nullable=False),
    sa.Column('ban_reason', sa.Text(), nullable=True),
    sa.Column('preferences', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), "postgresql"), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_shop_users_referral_code'), 'shop_users', ['referral_code'], unique=True)
    op.create_index(op.f('ix_shop_users_referred_by'), 'shop_users', ['referred_by'], unique=False)
    op.create_index('ix_shop_users_telegram', 'shop_users', ['telegram_id'], unique=False)
    op.create_index(op.f('ix_shop_users_telegram_id'), 'shop_users', ['telegram_id'], unique=True)
    op.create_table('users',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('username', sa.String(length=128), nullable=True),
    sa.Column('first_name', sa.String(length=255), nullable=True),
    sa.Column('last_name', sa.String(length=255), nullable=True),
    sa.Column('is_bot', sa.Boolean(), nullable=False),
    sa.Column('account_created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('first_seen_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('affiliate_links',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('referrer_id', sa.Integer(), nullable=False),
    sa.Column('referred_id', sa.Integer(), nullable=False),
    sa.Column('first_purchase_commission_pct', sa.Float(), nullable=False),
    sa.Column('lifetime_commission_pct', sa.Float(), nullable=False),
    sa.Column('total_commission_earned', sa.Float(), nullable=False),
    sa.Column('is_flagged', sa.Boolean(), nullable=False),
    sa.Column('flag_reason', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['referred_id'], ['shop_users.id'], ),
    sa.ForeignKeyConstraint(['referrer_id'], ['shop_users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('referred_id')
    )
    op.create_index(op.f('ix_affiliate_links_referrer_id'), 'affiliate_links', ['referrer_id'], unique=False)
    op.create_table('group_members',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('group_id', sa.BigInteger(), nullable=False),
    sa.Column('trust_score', sa.Float(), nullable=False),
    sa.Column('risk_index', sa.Float(), nullable=False),
    sa.Column('violation_count', sa.Integer(), nullable=False),
    sa.Column('warn_count', sa.Integer(), nullable=False),
    sa.Column('is_whitelisted', sa.Boolean(), nullable=False),
    sa.Column('is_blacklisted', sa.Boolean(), nullable=False),
    sa.Column('is_muted', sa.Boolean(), nullable=False),
    sa.Column('mute_until', sa.DateTime(timezone=True), nullable=True),
    sa.Column('joined_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['group_id'], ['groups.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_group_member_unique', 'group_members', ['user_id', 'group_id'], unique=True)
    op.create_index(op.f('ix_group_members_group_id'), 'group_members', ['group_id'], unique=False)
    op.create_index(op.f('ix_group_members_user_id'), 'group_members', ['user_id'], unique=False)
    op.create_table('moderation_events',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('group_id', sa.BigInteger(), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('message_id', sa.BigInteger(), nullable=True),
    sa.Column('message_text', sa.Text(), nullable=True),
    sa.Column('message_fingerprint', sa.String(length=64), nullable=True),
    sa.Column('violation_category', sa.Enum('SPAM', 'FLOOD', 'TOXICITY', 'NSFW', 'PHISHING', 'RAID', 'DUPLICATE', 'INVITE_ABUSE', 'MENTION_SPAM', 'MEDIA_SPAM', 'OTHER', name='violationcategory'), nullable=False),
    sa.Column('action_taken', sa.Enum('ALLOW', 'SILENT_LOG', 'DELETE', 'WARN', 'MUTE_TEMP', 'BAN_TEMP', 'BAN_PERM', 'ESCALATE', 'RAID_LOCKDOWN', 'SLOW_MODE', 'MEDIA_RESTRICT', 'LINK_RESTRICT', name='actiontype'), nullable=False),
    sa.Column('risk_score', sa.Float(), nullable=False),
    sa.Column('toxicity_score', sa.Float(), nullable=True),
    sa.Column('nsfw_score', sa.Float(), nullable=True),
    sa.Column('spam_score', sa.Float(), nullable=True),
    sa.Column('link_risk_score', sa.Float(), nullable=True),
    sa.Column('behavioral_risk', sa.Float(), nullable=True),
    sa.Column('explanation', sa.Text(), nullable=True),
    sa.Column('signals', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), "postgresql"), nullable=False),
    sa.Column('dry_run', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['group_id'], ['groups.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_events_group_created', 'moderation_events', ['group_id', 'created_at'], unique=False)
    op.create_index('ix_events_user_created', 'moderation_events', ['user_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_moderation_events_created_at'), 'moderation_events', ['created_at'], unique=False)
    op.create_index(op.f('ix_moderation_events_group_id'), 'moderation_events', ['group_id'], unique=False)
    op.create_index(op.f('ix_moderation_events_user_id'), 'moderation_events', ['user_id'], unique=False)
    op.create_table('notifications',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('notification_type', sa.Enum('TRANSACTIONAL', 'MARKETING', 'SYSTEM', name='notificationtype'), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('is_sent', sa.Boolean(), nullable=False),
    sa.Column('is_read', sa.Boolean(), nullable=False),
    sa.Column('extra_data', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), "postgresql"), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['shop_users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_notifications_created_at'), 'notifications', ['created_at'], unique=False)
    op.create_index(op.f('ix_notifications_user_id'), 'notifications', ['user_id'], unique=False)
    op.create_table('services',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('title_ar', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('category_id', sa.Integer(), nullable=True),
    sa.Column('base_price', sa.Float(), nullable=False),
    sa.Column('dynamic_price', sa.Float(), nullable=True),
    sa.Column('min_price', sa.Float(), nullable=False),
    sa.Column('max_price', sa.Float(), nullable=True),
    sa.Column('service_type', sa.Enum('INSTANT', 'MANUAL', 'HYBRID', name='servicetype'), nullable=False),
    sa.Column('api_endpoint', sa.String(length=512), nullable=True),
    sa.Column('api_params', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), "postgresql"), nullable=False),
    sa.Column('stock', sa.Integer(), nullable=True),
    sa.Column('min_order', sa.Integer(), nullable=False),
    sa.Column('max_order', sa.Integer(), nullable=True),
    sa.Column('delivery_time_minutes', sa.Integer(), nullable=False),
    sa.Column('rating', sa.Float(), nullable=False),
    sa.Column('total_orders', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_featured', sa.Boolean(), nullable=False),
    sa.Column('is_vip_only', sa.Boolean(), nullable=False),
    sa.Column('required_level', sa.Enum('BRONZE', 'SILVER', 'GOLD', 'ELITE', name='userlevel'), nullable=True),
    sa.Column('tags', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), "postgresql"), nullable=False),
    sa.Column('extra_data', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), "postgresql"), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['service_categories.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_services_category_id'), 'services', ['category_id'], unique=False)
    op.create_table('shop_orders',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('order_ref', sa.String(length=32), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('CREATED', 'VALIDATED', 'PAID', 'PROCESSING', 'COMPLETED', 'FAILED', 'REFUNDED', 'CANCELLED', name='orderstatus'), nullable=False),
    sa.Column('priority', sa.Enum('HIGH', 'NORMAL', 'LOW', name='orderpriority'), nullable=False),
    sa.Column('subtotal', sa.Float(), nullable=False),
    sa.Column('discount_amount', sa.Float(), nullable=False),
    sa.Column('total_amount', sa.Float(), nullable=False),
    sa.Column('coupon_id', sa.Integer(), nullable=True),
    sa.Column('coupon_discount', sa.Float(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('delivery_data', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), "postgresql"), nullable=False),
    sa.Column('retry_count', sa.Integer(), nullable=False),
    sa.Column('max_retries', sa.Integer(), nullable=False),
    sa.Column('sla_deadline', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('failed_reason', sa.Text(), nullable=True),
    sa.Column('xp_awarded', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['coupon_id'], ['coupons.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['shop_users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_orders_created', 'shop_orders', ['created_at'], unique=False)
    op.create_index('ix_orders_user_status', 'shop_orders', ['user_id', 'status'], unique=False)
    op.create_index(op.f('ix_shop_orders_created_at'), 'shop_orders', ['created_at'], unique=False)
    op.create_index(op.f('ix_shop_orders_order_ref'), 'shop_orders', ['order_ref'], unique=True)
    op.create_index(op.f('ix_shop_orders_user_id'), 'shop_orders', ['user_id'], unique=False)
    op.create_table('user_missions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('mission_type', sa.String(length=64), nullable=False),
    sa.Column('mission_date', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('is_completed', sa.Boolean(), nullable=False),
    sa.Column('reward_xp', sa.Integer(), nullable=False),
    sa.Column('reward_balance', sa.Float(), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['shop_users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_missions_user_date', 'user_missions', ['user_id', 'mission_date'], unique=False)
    op.create_index(op.f('ix_user_missions_user_id'), 'user_missions', ['user_id'], unique=False)
    op.create_table('affiliate_commissions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('referrer_id', sa.Integer(), nullable=False),
    sa.Column('referred_id', sa.Integer(), nullable=False),
    sa.Column('order_id', sa.Integer(), nullable=False),
    sa.Column('commission_amount', sa.Float(), nullable=False),
    sa.Column('commission_pct', sa.Float(), nullable=False),
    sa.Column('is_first_purchase', sa.Boolean(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['order_id'], ['shop_orders.id'], ),
    sa.ForeignKeyConstraint(['referred_id'], ['shop_users.id'], ),
    sa.ForeignKeyConstraint(['referrer_id'], ['shop_users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_affiliate_commissions_referred_id'), 'affiliate_commissions', ['referred_id'], unique=False)
    op.create_index(op.f('ix_affiliate_commissions_referrer_id'), 'affiliate_commissions', ['referrer_id'], unique=False)
    op.create_table('bundle_items',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('bundle_id', sa.Integer(), nullable=False),
    sa.Column('service_id', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['bundle_id'], ['bundles.id'], ),
    sa.ForeignKeyConstraint(['service_id'], ['services.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_bundle_items_bundle_id'), 'bundle_items', ['bundle_id'], unique=False)
    op.create_index(op.f('ix_bundle_items_service_id'), 'bundle_items', ['service_id'], unique=False)
    op.create_table('coupon_usages',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('coupon_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('order_id', sa.Integer(), nullable=False),
    sa.Column('discount_applied', sa.Float(), nullable=False),
    sa.Column('used_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['coupon_id'], ['coupons.id'], ),
    sa.ForeignKeyConstraint(['order_id'], ['shop_orders.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['shop_users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_coupon_usage_user_coupon', 'coupon_usages', ['user_id', 'coupon_id'], unique=False)
    op.create_index(op.f('ix_coupon_usages_coupon_id'), 'coupon_usages', ['coupon_id'], unique=False)
    op.create_index(op.f('ix_coupon_usages_user_id'), 'coupon_usages', ['user_id'], unique=False)
    op.create_table('shop_order_items',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('order_id', sa.Integer(), nullable=False),
    sa.Column('service_id', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('unit_price', sa.Float(), nullable=False),
    sa.Column('total_price', sa.Float(), nullable=False),
    sa.Column('delivery_value', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['order_id'], ['shop_orders.id'], ),
    sa.ForeignKeyConstraint(['service_id'], ['services.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_shop_order_items_order_id'), 'shop_order_items', ['order_id'], unique=False)
    op.create_index(op.f('ix_shop_order_items_service_id'), 'shop_order_items', ['service_id'], unique=False)
    op.create_table('shop_transactions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('ref', sa.String(length=64), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('tx_type', sa.Enum('DEPOSIT', 'PURCHASE', 'REFUND', 'COMMISSION', 'BONUS', 'ADJUSTMENT', name='transactiontype'), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('balance_before', sa.Float(), nullable=False),
    sa.Column('balance_after', sa.Float(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'COMPLETED', 'FAILED', 'LOCKED', name='transactionstatus'), nullable=False),
    sa.Column('order_id', sa.Integer(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('extra_data', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), "postgresql"), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['order_id'], ['shop_orders.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['shop_users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_shop_transactions_created_at'), 'shop_transactions', ['created_at'], unique=False)
    op.create_index(op.f('ix_shop_transactions_ref'), 'shop_transactions', ['ref'], unique=True)
    op.create_index(op.f('ix_shop_transactions_user_id'), 'shop_transactions', ['user_id'], unique=False)
    op.create_index('ix_transactions_user_created', 'shop_transactions', ['user_id', 'created_at'], unique=False)
    op.create_table('support_tickets',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('ticket_ref', sa.String(length=16), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('order_id', sa.Integer(), nullable=True),
    sa.Column('category', sa.String(length=64), nullable=False),
    sa.Column('subject', sa.String(length=255), nullable=False),
    sa.Column('status', sa.Enum('OPEN', 'IN_PROGRESS', 'WAITING', 'RESOLVED', 'CLOSED', 'ESCALATED', name='ticketstatus'), nullable=False),
    sa.Column('priority', sa.Enum('LOW', 'NORMAL', 'HIGH', 'URGENT', name='ticketpriority'), nullable=False),
    sa.Column('sla_deadline', sa.DateTime(timezone=True), nullable=True),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('escalated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('admin_notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['order_id'], ['shop_orders.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['shop_users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_support_tickets_created_at'), 'support_tickets', ['created_at'], unique=False)
    op.create_index(op.f('ix_support_tickets_ticket_ref'), 'support_tickets', ['ticket_ref'], unique=True)
    op.create_index(op.f('ix_support_tickets_user_id'), 'support_tickets', ['user_id'], unique=False)
    op.create_table('ticket_messages',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('ticket_id', sa.Integer(), nullable=False),
    sa.Column('sender_id', sa.BigInteger(), nullable=True),
    sa.Column('is_admin', sa.Boolean(), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('attachments', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), "postgresql"), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['ticket_id'], ['support_tickets.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ticket_messages_ticket_id'), 'ticket_messages', ['ticket_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_ticket_messages_ticket_id'), table_name='ticket_messages')
    op.drop_table('ticket_messages')
    op.drop_index(op.f('ix_support_tickets_user_id'), table_name='support_tickets')
    op.drop_index(op.f('ix_support_tickets_ticket_ref'), table_name='support_tickets')
    op.drop_index(op.f('ix_support_tickets_created_at'), table_name='support_tickets')
    op.drop_table('support_tickets')
    op.drop_index('ix_transactions_user_created', table_name='shop_transactions')
    op.drop_index(op.f('ix_shop_transactions_user_id'), table_name='shop_transactions')
    op.drop_index(op.f('ix_shop_transactions_ref'), table_name='shop_transactions')
    op.drop_index(op.f('ix_shop_transactions_created_at'), table_name='shop_transactions')
    op.drop_table('shop_transactions')
    op.drop_index(op.f('ix_shop_order_items_service_id'), table_name='shop_order_items')
    op.drop_index(op.f('ix_shop_order_items_order_id'), table_name='shop_order_items')
    op.drop_table('shop_order_items')
    op.drop_index(op.f('ix_coupon_usages_user_id'), table_name='coupon_usages')
    op.drop_index(op.f('ix_coupon_usages_coupon_id'), table_name='coupon_usages')
    op.drop_index('ix_coupon_usage_user_coupon', table_name='coupon_usages')
    op.drop_table('coupon_usages')
    op.drop_index(op.f('ix_bundle_items_service_id'), table_name='bundle_items')
    op.drop_index(op.f('ix_bundle_items_bundle_id'), table_name='bundle_items')
    op.drop_table('bundle_items')
    op.drop_index(op.f('ix_affiliate_commissions_referrer_id'), table_name='affiliate_commissions')
    op.drop_index(op.f('ix_affiliate_commissions_referred_id'), table_name='affiliate_commissions')
    op.drop_table('affiliate_commissions')
    op.drop_index(op.f('ix_user_missions_user_id'), table_name='user_missions')
    op.drop_index('ix_missions_user_date', table_name='user_missions')
    op.drop_table('user_missions')
    op.drop_index(op.f('ix_shop_orders_user_id'), table_name='shop_orders')
    op.drop_index(op.f('ix_shop_orders_order_ref'), table_name='shop_orders')
    op.drop_index(op.f('ix_shop_orders_created_at'), table_name='shop_orders')
    op.drop_index('ix_orders_user_status', table_name='shop_orders')
    op.drop_index('ix_orders_created', table_name='shop_orders')
    op.drop_table('shop_orders')
    op.drop_index(op.f('ix_services_category_id'), table_name='services')
    op.drop_table('services')
    op.drop_index(op.f('ix_notifications_user_id'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_created_at'), table_name='notifications')
    op.drop_table('notifications')
    op.drop_index(op.f('ix_moderation_events_user_id'), table_name='moderation_events')
    op.drop_index(op.f('ix_moderation_events_group_id'), table_name='moderation_events')
    op.drop_index(op.f('ix_moderation_events_created_at'), table_name='moderation_events')
    op.drop_index('ix_events_user_created', table_name='moderation_events')
    op.drop_index('ix_events_group_created', table_name='moderation_events')
    op.drop_table('moderation_events')
    op.drop_index(op.f('ix_group_members_user_id'), table_name='group_members')
    op.drop_index(op.f('ix_group_members_group_id'), table_name='group_members')
    op.drop_index('ix_group_member_unique', table_name='group_members')
    op.drop_table('group_members')
    op.drop_index(op.f('ix_affiliate_links_referrer_id'), table_name='affiliate_links')
    op.drop_table('affiliate_links')
    op.drop_table('users')
    op.drop_index(op.f('ix_shop_users_telegram_id'), table_name='shop_users')
    op.drop_index('ix_shop_users_telegram', table_name='shop_users')
    op.drop_index(op.f('ix_shop_users_referred_by'), table_name='shop_users')
    op.drop_index(op.f('ix_shop_users_referral_code'), table_name='shop_users')
    op.drop_table('shop_users')
    op.drop_table('service_categories')
    op.drop_table('groups')
    op.drop_index(op.f('ix_domain_reputation_domain'), table_name='domain_reputation')
    op.drop_table('domain_reputation')
    op.drop_index(op.f('ix_coupons_code'), table_name='coupons')
    op.drop_table('coupons')
    op.drop_table('bundles')
    op.drop_table('blacklisted_patterns')
    # ### end Alembic commands ###
